H_ENTRY = StaticIssue
H_CBMCFLAGS =
H_INSTFLAGS = #--nondet-volatile
H_OBJS = $(ENTRY)_harness.goto $(FREERTOS)/lib/FreeRTOS/tasks.goto $(FREERTOS)/lib/FreeRTOS/list.goto
H_DEF = -DSTACK_DEPTH=10

include ../Makefile.common