H_ENTRY = TaskGetState
H_CBMCFLAGS = #--nondet-static
H_OBJS = $(ENTRY)_harness.goto $(FREERTOS)/lib/FreeRTOS/tasks.goto #$(FREERTOS)/lib/FreeRTOS/list.goto
# H_DEF = -DSTACK_DEPTH=10

include ../Makefile.common